baseURL: https://deescuderoo.github.io
languageCode: "en-us"
title: "Personal Website and Blog"
theme: "my-hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Publications
      url: "publications/"
      weight: 3
    - name: Talks
      url: "talks/"
      weight: 4
    - name: Dissemination
      url: "dissemination/"
      weight: 5
    - name: Teaching
      url: "teaching/"
      weight: 6
    - name: Music
      url: "music/"
      weight: 7
    - name: Seminar
      url: "seminar/"
      weight: 8
    # - name: Resources
    #   url: "resources/"
    #   weight: 8

params:
  description: "A website built through Hugo and blogdown."
  footer: "Template from Yihui Xie (https://yihui.org) 2017 -- 2020"
  show-date: 0

markup:
  goldmark:
    renderer:
      unsafe: true

