---
title: "Dissemination"
date: 
draft: false
---

* A Crash Course on MPC
I am working on a series of posts explaining MPC from the ground up.

The following are the current posts online:
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-0-311fae2ce184][Part 0, Introduction]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-1-791c3e351d3c][Part 1, Basic Terminology and Essential Results]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-2-fe6f847640ae][Part 2, Two-Party Computation using Beaver/Multiplication Triples]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-3-c3f302153929][Part 3, Shamir Secret-Sharing]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-4-789eca123593][Part 4, Honest-Majority MPC with Passive Security]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-5-8171386754ef][Part 5, Error Detection and Error Correction]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-6-7728c985d16][Part 6: MPC with Active Security for t<n/3]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-7-23272abd3cd9][Part 7: Honest-Majority MPC with Active Security]]
- [[https://medium.com/applied-mpc/a-crash-course-on-mpc-part-8-363374202e6][Part 8: Two-Party MPC with Active Security]]

* An Introduction to Secret-Sharing-Based Secure Multiparty Computation

I'm in the process of writing an accessible, comprehensive and self-contained introduction to (secret-sharing) based multiparty computation.
This text serves as a general guide to this topic, focusing more on practical aspects of the techniques and constructions rather than their theoretical grounds. It is intended to serve as an introductory reference text for readers interested in the area, assuming essentially no background in these topics.

This work in progress currently includes an introduction to several core concepts in secure multiparty computation, an overview of simulation-based security, and detailed constructions for honest and two-thirds honest majority MPC, and also dishonest majority in the preprocessing model.

- [[https://eprint.iacr.org/2022/062.pdf][Link]]

* (In Spanish) A Course on MPC, FHE and ZKP

A master-level course I taught in Universidad Nacional de Colombia, Sede Medellín, on Secure Multiparty Computation, Fully Homomorphic Encryption, and Zero-Knowledge Proofs.

- Videos: https://youtube.com/playlist?list=PLeld-Hlf3EnrwZnvOT4IH5-2a-6HRaTG0

